# Generated by Django 3.1 on 2020-11-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, verbose_name='Le titre du todo')),
                ('descr', models.TextField(verbose_name='La description')),
                ('fait_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
